language: scala
scala:
   - 2.11.3
after_success:
   - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

# paste your api_key here
env:
  global:
   - secure: RHH/xGExKxkwIdNRJSWMd8gsTmS1B2ER7Uj9vJTW4c7A0IvB1CIdUXAumV9km6ZF+fRJNK8q20Ji8HTsSpuXxfDFYtGPcBY8uGzBhBHtkITatBLGfMBejQFq5dOBHZc4Ga/Oqdta+iUJBb7Dop6N+X7Bvvt7evUjYq0Zh/j8J/ccQjIgP5v3iy9hCl73ozkdfX/skJ7m/41/btSBXcpl0yDvua5FCmMOf5cZ4UoQIRNSIexJFbYh+UsmSlRAwgvQ9jJEtwVAdyLX3fRuf1psHRg3xeCjV9WBDDBiKDiRWVdfX1w5q5twWwu0jMywDhJv35bqTGOJFAqwx9Iwcc9LYRFjPTbtrrHIUM/nhpX+NOX6Q/eK8xtkk3z4K7ubHKf6Q8Z1vU8kKeuz+EPZt9yDdRcvR5wQX4UpkUXNWfIGcat3ET1kFykwGEkMlCXzB+h8WZzhlVISCqN2RBKGlHuLLn5IO9TB/jwy2+HAQHw3Bt2OT9GyeSMsVjrPHF9q7XErpjiwZFSxgg6m6sVQEfABWAIDK7yzHdK+8UgkNlNeuUeJ1Qpzn0JKotDtxqd5PzLQQ/hgdyVa0kXXXDKXyJT0kq6AUX1zCuduGT0LmbiRRT3CnYlJZGR/MLya5cFdVE54mUwbDtm0TznuB078We0VJ1ahISSYSDgEWXfDX9chUY8=
